import {poppins, bebas, tungsten, dinnext} from "./fonts"
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ProgressBar } from "./progress-bar";

export const metadata = {
  title: "Heroes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable} ${bebas.variable} ${tungsten.variable} ${dinnext.variable}`}>
      <body className={`bg-midnight ${poppins.className} antialiased`}>
        <ProgressBar className="fixed h-1 z-50 shadow-lg shadow-sky-500/20 bg-sky-500 top-12">
          <div className="relative">
            <Navbar />
            {children}
            <Footer />
          </div>
        </ProgressBar>
      </body>
    </html>
  );
}
