module.exports = [
  {
    heroId: 84,
    name: "Fiery Dance",
    icon: "/images/heroes/84/skins/Hero842-icon.png",
    portrait: "/images/heroes/84/skins/Hero842-portrait.png",
    splashArt: "/images/heroes/84/skins/Hero842-splashart.jpg",
  },
  {
    heroId: 84,
    name: "Street Punk",
    icon: "/images/heroes/84/skins/Hero843-icon.png",
    portrait: "/images/heroes/84/skins/Hero843-portrait.png",
    splashArt: "/images/heroes/84/skins/Hero843-splashart.jpg",
    skinTagId: 21,
  },
  {
    heroId: 84,
    name: "Night Shade",
    icon: "/images/heroes/84/skins/Hero844-icon.png",
    portrait: "/images/heroes/84/skins/Hero844-portrait.png",
    splashArt: "/images/heroes/84/skins/Hero844-splashart.jpg",
    skinTagId: 38,
  },
  {
    heroId: 84,
    name: "Cosmo Guard",
    icon: "/images/heroes/84/skins/Hero845-icon.png",
    portrait: "/images/heroes/84/skins/Hero845-portrait.png",
    splashArt: "/images/heroes/84/skins/Hero845-splashart.jpg",
    skinTagId: 2,
  },
  {
    heroId: 84,
    name: "Serene Plume",
    icon: "/images/heroes/84/skins/Hero846-icon.png",
    portrait: "/images/heroes/84/skins/Hero846-portrait.png",
    splashArt: "/images/heroes/84/skins/Hero846-splashart.jpg",
    skinTagId: 32,
  },
  {
    heroId: 84,
    name: "M-World Ling",
    icon: "/images/heroes/84/skins/Hero847-icon.png",
    portrait: "/images/heroes/84/skins/Hero847-portrait.png",
    splashArt: "/images/heroes/84/skins/Hero847-splashart.jpg",
    skinTagId: 13,
  },
  {
    heroId: 84,
    name: "Lord Shen",
    icon: "/images/heroes/84/skins/Hero848-icon.png",
    portrait: "/images/heroes/84/skins/Hero848-portrait.png",
    splashArt: "/images/heroes/84/skins/Hero848-splashart.jpg",
    skinTagId: 54,
  },
];
