module.exports = [
  {
    heroId: 68,
    name: "Bloody Mary",
    icon: "/images/heroes/68/skins/Hero682-icon.png",
    portrait: "/images/heroes/68/skins/Hero682-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero682-splashart.jpg",
  },
  {
    heroId: 68,
    name: "Cosmic Harmony",
    icon: "/images/heroes/68/skins/Hero683-icon.png",
    portrait: "/images/heroes/68/skins/Hero683-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero683-splashart.jpg",
    skinTagId: 1,
  },
  {
    heroId: 68,
    name: "Ash Blossom",
    icon: "/images/heroes/68/skins/Hero684-icon.png",
    portrait: "/images/heroes/68/skins/Hero684-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero684-splashart.jpg",
    skinTagId: 21,
  },
  {
    heroId: 68,
    name: "Libra",
    icon: "/images/heroes/68/skins/Hero685-icon.png",
    portrait: "/images/heroes/68/skins/Hero685-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero685-splashart.jpg",
    skinTagId: 36,
  },
  {
    heroId: 68,
    name: "Butterfly Seraphim",
    icon: "/images/heroes/68/skins/Hero686-icon.png",
    portrait: "/images/heroes/68/skins/Hero686-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero686-splashart.jpg",
    skinTagId: 31,
  },
  {
    heroId: 68,
    name: "Eyes of Eternity",
    icon: "/images/heroes/68/skins/Hero687-icon.png",
    portrait: "/images/heroes/68/skins/Hero687-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero687-splashart.jpg",
    skinTagId: 3,
  },
  {
    heroId: 68,
    name: "Dawn Revelation",
    icon: "/images/heroes/68/skins/Hero688-icon.png",
    portrait: "/images/heroes/68/skins/Hero688-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero688-splashart.jpg",
    skinTagId: 3,
  },
  {
    heroId: 68,
    name: "Divine Goddess",
    icon: "/images/heroes/68/skins/Hero689-icon.png",
    portrait: "/images/heroes/68/skins/Hero689-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero689-splashart.jpg",
    skinTagId: 60,
  },
  {
    heroId: 68,
    name: "Nature's Harmony",
    icon: "/images/heroes/68/skins/Hero6810-icon.png",
    portrait: "/images/heroes/68/skins/Hero6810-portrait.png",
    splashArt: "/images/heroes/68/skins/Hero6810-splashart.jpg",
    skinTagId: 1,
  },
];
