export const dataHero = [
  {
    id: 1,
    name: "Miya",
    roles: ["Marksman"],
    portrait: "/images/heroes/1/Hero011-portrait.png",
    difficulty: 1,
  },
  {
    id: 2,
    name: "Balmond",
    roles: ["Fighter"],
    portrait: "/images/heroes/2/Hero021-portrait.png",
    difficulty: 1,
  },
  {
    id: 3,
    name: "Saber",
    roles: ["Assassin"],
    portrait: "/images/heroes/3/Hero031-portrait.png",
    difficulty: 1,
  },
  {
    id: 4,
    name: "Alice",
    roles: ["Mage", "Tank"],
    portrait: "/images/heroes/4/Hero041-portrait.png",
    difficulty: 7,
  },
  {
    id: 5,
    name: "Nana",
    roles: ["Mage"],
    portrait: "/images/heroes/5/Hero051-portrait.png",
    difficulty: 1,
  },
  {
    id: 6,
    name: "Tigreal",
    roles: ["Tank"],
    portrait: "/images/heroes/6/Hero061-portrait.png",
    difficulty: 1,
  },
  {
    id: 7,
    name: "Alucard",
    roles: ["Fighter", "Assassin"],
    portrait: "/images/heroes/7/Hero071-portrait.png",
    difficulty: 4,
  },
  {
    id: 8,
    name: "Karina",
    roles: ["Assassin"],
    portrait: "/images/heroes/8/Hero081-portrait.png",
    difficulty: 4,
  },
  {
    id: 9,
    name: "Akai",
    roles: ["Tank"],
    portrait: "/images/heroes/9/Hero091-portrait.png",
    difficulty: 3,
  },
  {
    id: 10,
    name: "Franco",
    roles: ["Tank"],
    portrait: "/images/heroes/10/Hero101-portrait.png",
    difficulty: 2,
  },
  {
    id: 11,
    name: "Bane",
    roles: ["Fighter", "Mage"],
    portrait: "/images/heroes/11/Hero111-portrait.png",
    difficulty: 3,
  },
  {
    id: 12,
    name: "Bruno",
    roles: ["Marksman"],
    portrait: "/images/heroes/12/Hero121-portrait.png",
    difficulty: 5,
  },
  {
    id: 13,
    name: "Clint",
    roles: ["Marksman"],
    portrait: "/images/heroes/13/Hero131-portrait.png",
    difficulty: 7,
  },
  {
    id: 14,
    name: "Rafaela",
    roles: ["Support"],
    portrait: "/images/heroes/14/Hero141-portrait.png",
    difficulty: 2,
  },
  {
    id: 15,
    name: "Eudora",
    roles: ["Mage"],
    portrait: "/images/heroes/15/Hero151-portrait.png",
    difficulty: 1,
  },
  {
    id: 16,
    name: "Zilong",
    roles: ["Fighter", "Assassin"],
    portrait: "/images/heroes/16/Hero161-portrait.png",
    difficulty: 1,
  },
  {
    id: 17,
    name: "Fanny",
    roles: ["Assassin"],
    portrait: "/images/heroes/17/Hero171-portrait.png",
    difficulty: 10,
  },
  {
    id: 18,
    name: "Layla",
    roles: ["Marksman"],
    portrait: "/images/heroes/18/Hero181-portrait.png",
    difficulty: 1,
  },
  {
    id: 19,
    name: "Minotaur",
    roles: ["Tank", "Support"],
    portrait: "/images/heroes/19/Hero191-portrait.png",
    difficulty: 4,
  },
  {
    id: 20,
    name: "Lolita",
    roles: ["Support", "Tank"],
    portrait: "/images/heroes/20/Hero201-portrait.png",
    difficulty: 4,
  },
  {
    id: 21,
    name: "Hayabusa",
    roles: ["Assassin"],
    portrait: "/images/heroes/21/Hero211-portrait.png",
    difficulty: 5,
  },
  {
    id: 22,
    name: "Freya",
    roles: ["Fighter"],
    portrait: "/images/heroes/22/Hero221-portrait.png",
    difficulty: 5,
  },
  {
    id: 23,
    name: "Gord",
    roles: ["Mage"],
    portrait: "/images/heroes/23/Hero231-portrait.png",
    difficulty: 2,
  },
  {
    id: 24,
    name: "Natalia",
    roles: ["Assassin"],
    portrait: "/images/heroes/24/Hero241-portrait.png",
    difficulty: 9,
  },
  {
    id: 25,
    name: "Kagura",
    roles: ["Mage"],
    portrait: "/images/heroes/25/Hero251-portrait.png",
    difficulty: 8,
  },
  {
    id: 26,
    name: "Chou",
    roles: ["Fighter"],
    portrait: "/images/heroes/26/Hero261-portrait.png",
    difficulty: 7,
  },
  {
    id: 27,
    name: "Sun",
    roles: ["Fighter"],
    portrait: "/images/heroes/27/Hero271-portrait.png",
    difficulty: 3,
  },
  {
    id: 28,
    name: "Alpha",
    roles: ["Fighter"],
    portrait: "/images/heroes/28/Hero281-portrait.png",
    difficulty: 1,
  },
  {
    id: 29,
    name: "Ruby",
    roles: ["Fighter"],
    portrait: "/images/heroes/29/Hero291-portrait.png",
    difficulty: 4,
  },
  {
    id: 30,
    name: "Yi Sun-shin",
    roles: ["Assassin", "Marksman"],
    portrait: "/images/heroes/30/Hero301-portrait.png",
    difficulty: 7,
  },
  {
    id: 31,
    name: "Moskov",
    roles: ["Marksman"],
    portrait: "/images/heroes/31/Hero311-portrait.png",
    difficulty: 5,
  },
  {
    id: 32,
    name: "Johnson",
    roles: ["Tank", "Support"],
    portrait: "/images/heroes/32/Hero321-portrait.png",
    difficulty: 5,
  },
  {
    id: 33,
    name: "Cyclops",
    roles: ["Mage"],
    portrait: "/images/heroes/33/Hero331-portrait.png",
    difficulty: 6,
  },
  {
    id: 34,
    name: "Estes",
    roles: ["Support"],
    portrait: "/images/heroes/34/Hero341-portrait.png",
    difficulty: 3,
  },
  {
    id: 35,
    name: "Hilda",
    roles: ["Fighter", "Tank"],
    portrait: "/images/heroes/35/Hero351-portrait.png",
    difficulty: 4,
  },
  {
    id: 36,
    name: "Aurora",
    roles: ["Mage"],
    portrait: "/images/heroes/36/Hero361-portrait.png",
    difficulty: 1,
  },
  {
    id: 37,
    name: "Lapu-Lapu",
    roles: ["Fighter"],
    portrait: "/images/heroes/37/Hero371-portrait.png",
    difficulty: 5,
  },
  {
    id: 38,
    name: "Vexana",
    roles: ["Mage"],
    portrait: "/images/heroes/38/Hero381-portrait.png",
    difficulty: 1,
  },
  {
    id: 39,
    name: "Roger",
    roles: ["Fighter", "Marksman"],
    portrait: "/images/heroes/39/Hero391-portrait.png",
    difficulty: 5,
  },
  {
    id: 40,
    name: "Karrie",
    roles: ["Marksman"],
    portrait: "/images/heroes/40/Hero401-portrait.png",
    difficulty: 4,
  },
  {
    id: 41,
    name: "Gatotkaca",
    roles: ["Tank", "Fighter"],
    portrait: "/images/heroes/41/Hero411-portrait.png",
    difficulty: 1,
  },
  {
    id: 42,
    name: "Harley",
    roles: ["Assassin", "Mage"],
    portrait: "/images/heroes/42/Hero421-portrait.png",
    difficulty: 6,
  },
  {
    id: 43,
    name: "Irithel",
    roles: ["Marksman"],
    portrait: "/images/heroes/43/Hero431-portrait.png",
    difficulty: 5,
  },
  {
    id: 44,
    name: "Grock",
    roles: ["Tank", "Fighter"],
    portrait: "/images/heroes/44/Hero441-portrait.png",
    difficulty: 6,
  },
  {
    id: 45,
    name: "Argus",
    roles: ["Fighter"],
    portrait: "/images/heroes/45/Hero451-portrait.png",
    difficulty: 6,
  },
  {
    id: 46,
    name: "Odette",
    roles: ["Mage"],
    portrait: "/images/heroes/46/Hero461-portrait.png",
    difficulty: 2,
  },
  {
    id: 47,
    name: "Lancelot",
    roles: ["Assassin"],
    portrait: "/images/heroes/47/Hero471-portrait.png",
    difficulty: 5,
  },
  {
    id: 48,
    name: "Diggie",
    roles: ["Support"],
    portrait: "/images/heroes/48/Hero481-portrait.png",
    difficulty: 5,
  },
  {
    id: 49,
    name: "Hylos",
    roles: ["Tank"],
    portrait: "/images/heroes/49/Hero491-portrait.png",
    difficulty: 3,
  },
  {
    id: 50,
    name: "Zhask",
    roles: ["Mage"],
    portrait: "/images/heroes/50/Hero501-portrait.png",
    difficulty: 4,
  },
  {
    id: 51,
    name: "Helcurt",
    roles: ["Assassin"],
    portrait: "/images/heroes/51/Hero511-portrait.png",
    difficulty: 5,
  },
  {
    id: 52,
    name: "Pharsa",
    roles: ["Mage"],
    portrait: "/images/heroes/52/Hero521-portrait.png",
    difficulty: 3,
  },
  {
    id: 53,
    name: "Lesley",
    roles: ["Marksman", "Assassin"],
    portrait: "/images/heroes/53/Hero531-portrait.png",
    difficulty: 4,
  },
  {
    id: 54,
    name: "Jawhead",
    roles: ["Fighter"],
    portrait: "/images/heroes/54/Hero541-portrait.png",
    difficulty: 5,
  },
  {
    id: 55,
    name: "Angela",
    roles: ["Support"],
    portrait: "/images/heroes/55/Hero551-portrait.png",
    difficulty: 5,
  },
  {
    id: 56,
    name: "Gusion",
    roles: ["Assassin"],
    portrait: "/images/heroes/56/Hero561-portrait.png",
    difficulty: 8,
  },
  {
    id: 57,
    name: "Valir",
    roles: ["Mage"],
    portrait: "/images/heroes/57/Hero571-portrait.png",
    difficulty: 4,
  },
  {
    id: 58,
    name: "Martis",
    roles: ["Fighter"],
    portrait: "/images/heroes/58/Hero581-portrait.png",
    difficulty: 4,
  },
  {
    id: 59,
    name: "Uranus",
    roles: ["Tank"],
    portrait: "/images/heroes/59/Hero591-portrait.png",
    difficulty: 3,
  },
  {
    id: 60,
    name: "Hanabi",
    roles: ["Marksman"],
    portrait: "/images/heroes/60/Hero601-portrait.png",
    difficulty: 1,
  },
  {
    id: 61,
    name: "Chang'e",
    roles: ["Mage"],
    portrait: "/images/heroes/61/Hero611-portrait.png",
    difficulty: 3,
  },
  {
    id: 62,
    name: "Kaja",
    roles: ["Support", "Fighter"],
    portrait: "/images/heroes/62/Hero621-portrait.png",
    difficulty: 7,
  },
  {
    id: 63,
    name: "Selena",
    roles: ["Assassin", "Mage"],
    portrait: "/images/heroes/63/Hero631-portrait.png",
    difficulty: 7,
  },
  {
    id: 64,
    name: "Aldous",
    roles: ["Fighter"],
    portrait: "/images/heroes/64/Hero641-portrait.png",
    difficulty: 6,
  },
  {
    id: 65,
    name: "Claude",
    roles: ["Marksman"],
    portrait: "/images/heroes/65/Hero651-portrait.png",
    difficulty: 6,
  },
  {
    id: 66,
    name: "Vale",
    roles: ["Mage"],
    portrait: "/images/heroes/66/Hero661-portrait.png",
    difficulty: 2,
  },
  {
    id: 67,
    name: "Leomord",
    roles: ["Fighter"],
    portrait: "/images/heroes/67/Hero671-portrait.png",
    difficulty: 6,
  },
  {
    id: 68,
    name: "Lunox",
    roles: ["Mage"],
    portrait: "/images/heroes/68/Hero681-portrait.png",
    difficulty: 9,
  },
  {
    id: 69,
    name: "Hanzo",
    roles: ["Assassin"],
    portrait: "/images/heroes/69/Hero691-portrait.png",
    difficulty: 8,
  },
  {
    id: 70,
    name: "Belerick",
    roles: ["Tank"],
    portrait: "/images/heroes/70/Hero701-portrait.png",
    difficulty: 1,
  },
  {
    id: 71,
    name: "Kimmy",
    roles: ["Marksman", "Mage"],
    portrait: "/images/heroes/71/Hero711-portrait.png",
    difficulty: 9,
  },
  {
    id: 72,
    name: "Thamuz",
    roles: ["Fighter"],
    portrait: "/images/heroes/72/Hero721-portrait.png",
    difficulty: 4,
  },
  {
    id: 73,
    name: "Harith",
    roles: ["Mage"],
    portrait: "/images/heroes/73/Hero731-portrait.png",
    difficulty: 5,
  },
  {
    id: 74,
    name: "Minsitthar",
    roles: ["Fighter"],
    portrait: "/images/heroes/74/Hero741-portrait.png",
    difficulty: 4,
  },
  {
    id: 75,
    name: "Kadita",
    roles: ["Mage", "Assassin"],
    portrait: "/images/heroes/75/Hero751-portrait.png",
    difficulty: 6,
  },
  {
    id: 76,
    name: "Faramis",
    roles: ["Support", "Mage"],
    portrait: "/images/heroes/76/Hero761-portrait.png",
    difficulty: 4,
  },
  {
    id: 77,
    name: "Badang",
    roles: ["Fighter"],
    portrait: "/images/heroes/77/Hero771-portrait.png",
    difficulty: 1,
  },
  {
    id: 78,
    name: "Khufra",
    roles: ["Tank"],
    portrait: "/images/heroes/78/Hero781-portrait.png",
    difficulty: 5,
  },
  {
    id: 79,
    name: "Granger",
    roles: ["Marksman"],
    portrait: "/images/heroes/79/Hero791-portrait.png",
    difficulty: 4,
  },
  {
    id: 80,
    name: "Guinevere",
    roles: ["Fighter"],
    portrait: "/images/heroes/80/Hero801-portrait.png",
    difficulty: 4,
  },
  {
    id: 81,
    name: "Esmeralda",
    roles: ["Tank", "Mage"],
    portrait: "/images/heroes/81/Hero811-portrait.png",
    difficulty: 6,
  },
  {
    id: 82,
    name: "Terizla",
    roles: ["Fighter", "Tank"],
    portrait: "/images/heroes/82/Hero821-portrait.png",
    difficulty: 2,
  },
  {
    id: 83,
    name: "X.Borg",
    roles: ["Fighter"],
    portrait: "/images/heroes/83/Hero831-portrait.png",
    difficulty: 4,
  },
  {
    id: 84,
    name: "Ling",
    roles: ["Assassin"],
    portrait: "/images/heroes/84/Hero841-portrait.png",
    difficulty: 7,
  },
  {
    id: 85,
    name: "Dyrroth",
    roles: ["Fighter"],
    portrait: "/images/heroes/85/Hero851-portrait.png",
    difficulty: 5,
  },
  {
    id: 86,
    name: "Lylia",
    roles: ["Mage"],
    portrait: "/images/heroes/86/Hero861-portrait.png",
    difficulty: 5,
  },
  {
    id: 87,
    name: "Baxia",
    roles: ["Tank"],
    portrait: "/images/heroes/87/Hero871-portrait.png",
    difficulty: 2,
  },
  {
    id: 88,
    name: "Masha",
    roles: ["Fighter", "Tank"],
    portrait: "/images/heroes/88/Hero881-portrait.png",
    difficulty: 3,
  },
  {
    id: 89,
    name: "Wanwan",
    roles: ["Marksman"],
    portrait: "/images/heroes/89/Hero891-portrait.png",
    difficulty: 6,
  },
  {
    id: 90,
    name: "Silvanna",
    roles: ["Fighter"],
    portrait: "/images/heroes/90/Hero901-portrait.png",
    difficulty: 2,
  },
  {
    id: 91,
    name: "Cecilion",
    roles: ["Mage"],
    portrait: "/images/heroes/91/Hero911-portrait.png",
    difficulty: 4,
  },
  {
    id: 92,
    name: "Carmilla",
    roles: ["Support", "Tank"],
    portrait: "/images/heroes/92/Hero921-portrait.png",
    difficulty: 4,
  },
  {
    id: 93,
    name: "Atlas",
    roles: ["Tank"],
    portrait: "/images/heroes/93/Hero931-portrait.png",
    difficulty: 5,
  },
  {
    id: 94,
    name: "Popol and Kupa",
    roles: ["Marksman"],
    portrait: "/images/heroes/94/Hero941-portrait.png",
    difficulty: 5,
  },
  {
    id: 95,
    name: "Yu Zhong",
    roles: ["Fighter"],
    portrait: "/images/heroes/95/Hero951-portrait.png",
    difficulty: 7,
  },
  {
    id: 96,
    name: "Luo Yi",
    roles: ["Mage"],
    portrait: "/images/heroes/96/Hero961-portrait.png",
    difficulty: 5,
  },
  {
    id: 97,
    name: "Benedetta",
    roles: ["Assassin", "Fighter"],
    portrait: "/images/heroes/97/Hero971-portrait.png",
    difficulty: 7,
  },
  {
    id: 98,
    name: "Khaleed",
    roles: ["Fighter"],
    portrait: "/images/heroes/98/Hero981-portrait.png",
    difficulty: 5,
  },
  {
    id: 99,
    name: "Barats",
    roles: ["Tank", "Fighter"],
    portrait: "/images/heroes/99/Hero991-portrait.png",
    difficulty: 4,
  },
  {
    id: 100,
    name: "Brody",
    roles: ["Marksman"],
    portrait: "/images/heroes/100/Hero1001-portrait.png",
    difficulty: 5,
  },
  {
    id: 101,
    name: "Yve",
    roles: ["Mage"],
    portrait: "/images/heroes/101/Hero1011-portrait.png",
    difficulty: 7,
  },
  {
    id: 102,
    name: "Mathilda",
    roles: ["Support", "Assassin"],
    portrait: "/images/heroes/102/Hero1021-portrait.png",
    difficulty: 4,
  },
  {
    id: 103,
    name: "Paquito",
    roles: ["Fighter", "Assassin"],
    portrait: "/images/heroes/103/Hero1031-portrait.png",
    difficulty: 8,
  },
  {
    id: 104,
    name: "Gloo",
    roles: ["Tank"],
    portrait: "/images/heroes/104/Hero1041-portrait.png",
    difficulty: 7,
  },
  {
    id: 105,
    name: "Beatrix",
    roles: ["Marksman"],
    portrait: "/images/heroes/105/Hero1051-portrait.png",
    difficulty: 7,
  },
  {
    id: 106,
    name: "Phoveus",
    roles: ["Fighter"],
    portrait: "/images/heroes/106/Hero1061-portrait.png",
    difficulty: 4,
  },
  {
    id: 107,
    name: "Natan",
    roles: ["Marksman"],
    portrait: "/images/heroes/107/Hero1071-portrait.png",
    difficulty: 2,
  },
  {
    id: 108,
    name: "Aulus",
    roles: ["Fighter"],
    portrait: "/images/heroes/108/Hero1081-portrait.png",
    difficulty: 4,
  },
  {
    id: 109,
    name: "Aamon",
    roles: ["Assassin"],
    portrait: "/images/heroes/109/Hero1091-portrait.png",
    difficulty: 5,
  },
  {
    id: 110,
    name: "Valentina",
    roles: ["Mage"],
    portrait: "/images/heroes/110/Hero1101-portrait.png",
    difficulty: 8,
  },
  {
    id: 111,
    name: "Edith",
    roles: ["Tank", "Marksman"],
    portrait: "/images/heroes/111/Hero1111-portrait.png",
    difficulty: 3,
  },
  {
    id: 112,
    name: "Floryn",
    roles: ["Support"],
    portrait: "/images/heroes/112/Hero1121-portrait.png",
    difficulty: 1,
  },
  {
    id: 113,
    name: "Yin",
    roles: ["Fighter", "Assassin"],
    portrait: "/images/heroes/113/Hero1131-portrait.png",
    difficulty: 4,
  },
  {
    id: 114,
    name: "Melissa",
    roles: ["Marksman"],
    portrait: "/images/heroes/114/Hero1141-portrait.png",
    difficulty: 4,
  },
  {
    id: 115,
    name: "Xavier",
    roles: ["Mage"],
    portrait: "/images/heroes/115/Hero1151-portrait.png",
    difficulty: 3,
  },
  {
    id: 116,
    name: "Julian",
    roles: ["Fighter", "Mage"],
    portrait: "/images/heroes/116/Hero1161-portrait.png",
    difficulty: 2,
  },
  {
    id: 117,
    name: "Fredrinn",
    roles: ["Fighter", "Tank"],
    portrait: "/images/heroes/117/Hero1171-portrait.png",
    difficulty: 4,
  },
  {
    id: 118,
    name: "Joy",
    roles: ["Assassin"],
    portrait: "/images/heroes/118/Hero1181-portrait.png",
    difficulty: 9,
  },
  {
    id: 119,
    name: "Novaria",
    roles: ["Mage"],
    portrait: "/images/heroes/119/Hero1191-portrait.png",
    difficulty: 6,
  },
  {
    id: 120,
    name: "Arlott",
    roles: ["Fighter", "Assassin"],
    portrait: "/images/heroes/120/Hero1201-portrait.png",
    difficulty: 5,
  },
  {
    id: 121,
    name: "Ixia",
    roles: ["Marksman"],
    portrait: "/images/heroes/121/Hero1211-portrait.png",
    difficulty: 4,
  },
  {
    id: 122,
    name: "Nolan",
    roles: ["Assassin"],
    portrait: "/images/heroes/122/Hero1221-portrait.png",
    difficulty: 6,
  },
  {
    id: 123,
    name: "Cici",
    roles: ["Fighter"],
    portrait: "/images/heroes/123/Hero1231-portrait.png",
    difficulty: 2,
  },
  {
    id: 124,
    name: "Chip",
    roles: ["Support", "Tank"],
    portrait: "/images/heroes/124/Hero1241-portrait.png",
    difficulty: 6,
  },
  {
    id: 125,
    name: "Zhuxin",
    roles: ["Mage"],
    portrait: "/images/heroes/125/Hero1251-portrait.png",
    difficulty: 3,
  },
  {
    id: 126,
    name: "Suyou",
    roles: ["Assassin", "Fighter"],
    portrait: "/images/heroes/126/Hero1261-portrait.png",
    difficulty: 7,
  },
  {
    id: 127,
    name: "Lukas",
    roles: ["Fighter"],
    portrait: "/images/heroes/127/Hero1271-portrait.png",
    difficulty: 4,
  },
];
